FROM node:20-alpine AS node_build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY resources ./resources
COPY webpack.config.js postcss.config.js ./
RUN npm run build

FROM nginx:stable-alpine
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY public/index.php /var/www/html/public/index.php
COPY --from=node_build /app/public/build /var/www/html/public/build